### ISSUE TITLE
Owner of pool cannot unbond when requirements are met

### ISSUE THREAD

**Issue by Juanma0x** [polkadot-cloud/polkadot-staking-dashboard#2052]
After the nomination pool's state is set to "destroying" and all members have been removed, the owners of nomination pools cannot unbond an amount that would leave the pool below `nominationPools.minCreateBond`, using the Staking Dashboard.

However, pool owners can still unbond the full amount using the extrinsic `nominationPools.unbond`. Therefore, the limitation is due to the functionality of the Staking Dashboard.

Ideally, the Staking Dashboard should allow pool owners to unbond the entirety of their funds in the pool when the pool is set to "destroying" and there are no remaining members.

**Comment by chuacw** [comment]
Following @Juanma0x 's comment, I was able to unbond using the extrinsic. Unexpectedly, I didn't have to multiply by 10000000000. I entered the exact value of DOT, and I was able to unbond on the Polkadot portal with the extrinsic nominationPools unbond.

**Comment by rossbulat** [comment]
Fixed in https://github.com/polkadot-cloud/polkadot-staking-dashboard/pull/2370
