### ISSUE TITLE
Walletconnect support

### ISSUE THREAD

**Issue by Tbaut** [polkadot-cloud/polkadot-staking-dashboard#2127]
I know it's been closed in the past cf https://github.com/paritytech/polkadot-staking-dashboard/issues/1208
However, I couldn't find any open issue, and since this is part of the plan from the treasury proposal https://polkadot.polkassembly.io/treasury/569https://docs.google.com/document/d/1fn8HYi16_q-ScuRsKU-YPRaMV3IaPOHdaiPEyuIl9qM/edit#heading=h.io1j8tawyxbi I thought having an issue to track the delivery of this feature would be great. Very much looking forward to it!

**Comment by muddlebee** [comment]
+1

**Comment by rossbulat** [comment]
Thanks for re-opening @Tbaut. The stale bot will close issues after a period of inactivity to prevent them from building up. Indeed, WC is still on the agenda. Will ensure this issue stays open until addressed.

**Comment by mistercole** [comment]
Yes please!

**Comment by rossbulat** [comment]
Resolved in https://github.com/polkadot-cloud/polkadot-staking-dashboard/pull/2276
