### ISSUE TITLE
Unbond Max differs in polkadot.staking + substarte portal when nominating

### ISSUE THREAD

**Issue by niklasp** [polkadot-cloud/polkadot-staking-dashboard#2187]
When I use my account and try unbonding all my stake, polkadot staking dashboard shows a different value (than my currently active stake) after clicking the "Max" button. What is the reason for that? I would expect that I can unbond the total amount i bonded to staking.

<img width="627" alt="Bildschirmfoto 2024-07-08 um 16 04 47" src="https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/1685139/481b5503-b03d-4c1b-a2f1-a515ec3ff8d4">
(modal when clicking the minus in "Bonded Funds" Card)
<img width="1106" alt="Bildschirmfoto 2024-07-08 um 16 04 12" src="https://github.com/polkadot-cloud/polkadot-staking-dashboard/assets/1685139/5a0b61bc-c6ef-460e-a9e1-81bf0073cb15">
(substrate portal)

When clicking the "Unstake" button it will trigger a batch tx with "staking.chill" and "staking.unbond" where the unbond amount is my total bonded amount.

I am wondering if I am looking at a feature or a bug 🙃

related code: https://github.com/polkadot-cloud/polkadot-staking-dashboard/blob/7dd170a7a50cf1e6b41c5f68d65fcf9743acc8da/src/modals/Unbond/index.tsx#L99

**Comment by rossbulat** [comment]
Removing your bond in this module enforces the `minimumActiveStake` to remain bonded, otherwise the unbond request would return an error.

There is a dedicated button to unstake next to your status, which will submit a batch transaction of unbonding the full bond amount and chill.
