### ISSUE TITLE
New Filter: filter out validators without identity

### ISSUE THREAD

**Issue by rvalle** [polkadot-cloud/polkadot-staking-dashboard#2190]
I normally select validators that have an identity and are run by community members I can meet at community events, etc.

There are many unidentified validators which may be performant.

I would like to filter them out, just like 100% commission validators can be filtered out.

This would remove the noise and make it easier to select.

Also, it would be convenient to have the Prev/Next links also at the bottom, in particular when one is screening validators in reading order.

**Comment by rossbulat** [comment]
This filter exists but has been disabled until the People chain migration is complete for all the chains.

**Comment by rvalle** [comment]
ok, that makes sense.
