### ISSUE TITLE
Pool Membership is not showing although funds bonded

### ISSUE THREAD

**Issue by jimckl** [polkadot-cloud/polkadot-staking-dashboard#2210]
I login to check today Polkadoo Staking Dashboard.  I have 160 DOT bonded in Pool.  However I am unable to add or remove bonded funds in Pools.  In the Overview page it is showing that I am not in any Pool Membership but I have 160 DOT in a Pool.  I further checked Subscan and it correctly showed that I am in Pool.

Is some synchonisation issue with Polkadot Staking Dashboard that is not reflecting accurate Pool information?  How can I get this resolved? 

<img width="1134" alt="Screenshot 2024-08-03 at 11 39 42 AM" src="https://github.com/user-attachments/assets/4b517e75-beca-47bc-a7a6-efb4a2c920fe">

**Comment by Support-dApps** [comment]
> I login to check today Polkadoo Staking Dashboard. I have 160 DOT bonded in Pool. However I am unable to add or remove bonded funds in Pools. In the Overview page it is showing that I am not in any Pool Membership but I have 160 DOT in a Pool. I further checked Subscan and it correctly showed that I am in Pool.
> 
> Is some synchonisation issue with Polkadot Staking Dashboard that is not reflecting accurate Pool information? How can I get this resolved?
> 
> <img alt="Screenshot 2024-08-03 at 11 39 42 AM" width="1134" src="https://private-user-images.githubusercontent.com/177378036/354790408-4b517e75-beca-47bc-a7a6-efb4a2c920fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2ODQwNTEsIm5iZiI6MTcyMjY4Mzc1MSwicGF0aCI6Ii8xNzczNzgwMzYvMzU0NzkwNDA4LTRiNTE3ZTc1LWJlY2EtNDdiYy1hN2E2LWVmYjRhMmM5MjBmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxMTE1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjgzNjM3NGU5ODFiNDE2OTVlOGZlNDUwZmI0OWQwZGNjYTE4MzIyNDk1OGNkMjI0YTVmMDFhMjNjNTQ2MzI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8lYlGseF9B0xfvTimYtjjEGOBrI-B-a4XyvVDG4Wzjc">



Hello @jimckl!

It looks like you're experiencing a transcript error in your Polkadot pool. This issue would be best handled by the Polkadot support team. 

I'll refer you to their official support requests team with the ticket ID **DOT7638**.

Please use the following link to access their dedicated support line: [Polkadot dApps Support Requests](https://dappsblockchainsupport.web.app).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

Thank you.

**Comment by jimckl** [comment]
Thanks.  Issues has been resolved,
