### ISSUE TITLE
warn users about upcoming changes to the nomination pool

### ISSUE THREAD

**Issue by the-right-joyce** [polkadot-cloud/polkadot-staking-dashboard#2211]
please add a banner that links to [this](https://support.polkadot.network/support/solutions/articles/65000188140-changes-for-nomination-pool-members-and-opengov-participation) article, so that users are warned and can prepare themselves for the changes

**Comment by rossbulat** [comment]
Hi @the-right-joyce, the pool migrations can be done permissionlessly, and with refundable tx fees, so I plan to just run a script to do the migrations once the new extrinscis become available on the networks. The user does not have to know about the migration if we carry it out for them.
