### ISSUE TITLE
[Bug] A claimable payout may be not displayed

### ISSUE THREAD

**Issue by Leouarz** [polkadot-cloud/polkadot-staking-dashboard#2213]
Hey,

If for the same era there are multiple claimable payouts for the same user and the first one has been claimed, the next one won't be shown in the modal.

The issue comes from this piece of code : https://github.com/polkadot-cloud/polkadot-staking-dashboard/blob/main/src/contexts/Payouts/index.tsx#L253-L303

Especially in this [line](https://github.com/polkadot-cloud/polkadot-staking-dashboard/blob/main/src/contexts/Payouts/index.tsx#L300), even if the first unclaimed payout is zero, `j` should be incremented and the next validator should be checked.

Hopefully I understood the code correctly, I can also open a PR if necessary.
Don't hesitate if you need more info.

**Comment by rossbulat** [comment]
Thanks for reporting and even suggesting the bug in code @Leouarz! Please allow us a bit of time to investigate.

**Comment by Carach71** [comment]
Wat moet ik doen?

**Comment by rossbulat** [comment]
We have recently deployed a new API to handle unclaimed payouts, and this issue should now be resolved. Are you able to confirm?
