### ISSUE TITLE
Rate-limit = 0 response when using polkadot.api.subscan.io

### ISSUE THREAD

**Issue by chuacw** [polkadot-cloud/polkadot-staking-dashboard#2324]
The staking dashboard uses polkadot.api.subscan.io and when it uses the following:

- https://polkadot.api.subscan.io/api/v2/scan/account/reward_slash
- https://polkadot.api.subscan.io/api/scan/nomination_pool/rewards

"API rate limit exceeded" is returned.

**Comment by rossbulat** [comment]
Hi @chuacw, thanks for reporting this. Each user is currently restricted to the per IP address limit, I have this problem a lot in development when Subscan is enabled & things are constantly hot reloading.

This is an issue that is proving to be more problematic as we introduce more Subscan support. I have been debating in my mind whether to just launch an internal API service the dashboard can leverage with much higher rate limits. I initially thought this is a bit away from core value proposition, but recently I've been leaning towards actually doing this API service as a plugin to the dashboard.

Definitely an issue - we cannot introduce a Subscan API key as it'll be publicly accessible; dashboard is a static webpage & doesn't rely on a backend afterall. So this internal API service would probably only support the production staking.polkadot.cloud domain. We'd have a private endpoint for testing also.

**Comment by chuacw** [comment]
You should consider fixing this soon, because this has broken some functionality of the dashboard.

**Comment by rossbulat** [comment]
Closing as we have deployed the Staking API now (https://github.com/polkadot-cloud/polkadot-staking-dashboard/pull/2365). Pool rewards will also be served over this API shortly, but Subscan throttle limits should no longer be impacted.
