### ISSUE TITLE
My stake is blocked

### ISSUE THREAD

**Issue by asggWa** [polkadot-cloud/polkadot-staking-dashboard#2339]
Someone could help me. I need enought to pay fee. I will return the same wallet.

14wydAgfGo8QHs99QEmfcXbrN2vUpUD2hF68xsbmn8BuT8gk

**Comment by joeljkrb** [comment]
Hi,

We cannot assist with providing funds for fees. You will need to send additional DOT to your wallet to cover transaction fees.

Regards
